//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public byte attendanceId { get; set; }
        public byte courseId { get; set; }
        public byte lecturerId { get; set; }
        public string title { get; set; }
        public System.DateTime createdAt { get; set; }
        public string status { get; set; }
    
        public virtual Lecturer Lecturer { get; set; }
        public virtual Course Course { get; set; }
    }
}
