//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class StdAttendance
    {
        public byte std_attId { get; set; }
        public byte attendanceId { get; set; }
        public byte matricNo { get; set; }
        public string status { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
